### ISSUE TITLE
Any way to bisect using ASan builds with this tool?

### ISSUE THREAD

**Issue by svn-dys** [jay0lee/chrome-bisect#4]
Trying to bisect a Chromium issue, but would like to use ASan builds instead.

**Comment by jay0lee** [comment]
Try adding:
```
--asan
```
to your command line. You can also run:
```
chrome_bisect --help
```
to see all options.

**Comment by svn-dys** [comment]
Thank you for helping! 

I see this error:
```
chrome_bisect.exe -a win -g 1078752 -b 1078011 --asan -- --enable-features=Portals
running bisect-builds.py with options: -a win -g 1078752 -b 1078011 --asan --verify-range --use-local-cache -- --enable-features=Portals
Scanning from 1078752 to 1078011 (741 revisions).
Downloading list of known revisions...
Saved revisions 275883-852410 to C:\Users\SvenH\AppData\Local\Temp\_MEI255242\.bisect-builds-cache.json
Traceback (most recent call last):
  File "chrome_bisect.py", line 119, in <module>
  File "chrome_bisect.py", line 115, in main
  File "bisect_builds.py", line 1308, in main
  File "bisect_builds.py", line 845, in Bisect
  File "bisect_builds.py", line 491, in GetRevList
RuntimeError: Last available bisect revision for win is 852410. Try a different good/bad range.
[26080] Failed to execute script 'chrome_bisect' due to unhandled exception!
```

The bisect range is from 12/1 (1078011 ) - 12/2 (1078752)... which seems reasonable. I cannot bisect past 852410? Am I doing something wrong?

**Comment by svn-dys** [comment]
Hi, 

Anyway to fix this issue? I am trying to bisect a UAF that seems to only reproduce on ASan builds. I cannot bisect builds past rev 852410 with the --asan switch. :(

**Comment by jay0lee** [comment]
It seems to be an issue with the underlying script, not much I can do there
right now.

**Comment by svn-dys** [comment]
Any chance for a fix? Thank you.
